name: CI Workflow

on:
    push:
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: mvn clean install

