name: CI Workflow

on:
    push:
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: mvn clean install
            

            - name: Push Docker image
               uses: docker/build-push-action@v4
               with:
                context: .
                   file: ./Dockerfile
                   tags: username/repository:tag  # Replace with your Docker Hub repo and tag
                   push: true

