name: CI Workflow

on:
    push:
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: action/checkout@v3

            - name: Build
              run: mvn clean install

